fix: stale modelSlug (#100)
1. fix: remove definition of `currentConversation` as it is not used (to
fix the following error when running `npm run build:prd:chrome`
```bash
> webapp@0.0.0 build:prd:chrome
> bash -c 'source ./scripts/build-prd-chrome.sh'

🧩 Start building Chrome Extension ...
📦 Version: 2.16.0
📦 Monorepo Revision: 9fc435
📦 Beta Build: false
📦 API Endpoint: https://app.paperdebugger.com

❌ Failed to build Chrome Extension, please check logs/build.log

> webapp@0.0.0 build
> tsc -b && npm run _build:default && npm run _build:background && npm run _build:intermediate && npm run _build:settings && npm run _build:popup

src/views/settings/setting-text-input.tsx(32,13): error TS6133: 'currentConversation' is declared but its value is never read.
```
2. fix: change matching from substring to exact, to prevent
`gpt-4.1-mini` from matching to `gpt-4.0` (edit: typo, should be
`gpt-4.1`), making the method more robust to the order of supported
models defined.

3. [edit] refactor: use IsCustom and not redefine logic in NewAIClientV2